name: Deploy Ansible to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible
        
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible
        cd taller3
        
    - name: Run Ansible playbook
      run: |
        ansible-playbook crud.yml --private-key ~/.ssh/id_ed25519
